# https://aka.ms/yaml

name: "$(date:yyyyMMdd)$(rev:.r)"

trigger:
  - main

pr:
  - main

jobs:
  - job: PerfView_Debug
    pool:
      vmImage: 'windows-2022'
      name: Azure Pipelines
      demands:
      - msbuild
      - vstest
    variables:
      Codeql.Enabled: true
      Codeql.BuildIdentifier: PerfView

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1'
      inputs:
        version: 3.1.x

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet.exe'
      inputs:
        versionSpec: 6.3.0

    - task: NuGetCommand@2
      displayName: 'NuGet Restore PerfView.sln'
      inputs:
        restoreSolution: PerfView.sln
        feedsToUse: config
        includeNuGetOrg: false
        nugetConfigPath: '.\NuGet.config'

    - task: MSBuild@1
      displayName: 'Build PerfView.sln'
      inputs:
        solution: PerfView.sln
        configuration: Debug

    - task: VSTest@2
      displayName: 'Run Tests'
      inputs:
        testAssemblyVer2: |
         **\bin\**\LinuxTracingTests.dll
         **\bin\**\CtfTracingTests.dll
         **\bin\**\TraceEventTests.dll
         **\bin\**\PerfViewTests.dll
        testRunTitle: 'PerfView - Debug'
        runTestsInIsolation: true
        otherConsoleOptions: '--blame'

    - task: CopyFiles@2
      displayName: 'Copy Files to Artifacts Staging'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'PerfViewBinaries-Debug'
      condition: succeededOrFailed()

  - job: PerfView_Release
    pool:
      vmImage: 'windows-2022'
      name: Azure Pipelines
      demands:
      - msbuild
      - vstest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK 3.1'
      inputs:
        version: 3.1.x

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet.exe'
      inputs:
        versionSpec: 6.3.0

    - task: NuGetCommand@2
      displayName: 'NuGet Restore PerfView.sln'
      inputs:
        restoreSolution: PerfView.sln
        feedsToUse: config
        includeNuGetOrg: false
        nugetConfigPath: '.\NuGet.config'

    - task: MSBuild@1
      displayName: 'Build PerfView.sln'
      inputs:
        solution: PerfView.sln
        configuration: Release

    - task: VSTest@2
      displayName: 'Run Tests'
      inputs:
        testAssemblyVer2: |
         **\bin\**\LinuxTracingTests.dll
         **\bin\**\CtfTracingTests.dll
         **\bin\**\TraceEventTests.dll
         **\bin\**\PerfViewTests.dll
        testRunTitle: 'PerfView - Release'
        runTestsInIsolation: true
        otherConsoleOptions: '--blame'

    - task: CopyFiles@2
      displayName: 'Copy Files to Artifacts Staging'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'PerfViewBinaries-Release'

  - job: PerfCollect
    pool:
      vmImage: 'ubuntu-latest'
      name: Azure Pipelines

    steps:
    - task: DockerInstaller@0
      displayName: 'Install Docker'

    - task: Bash@3
      displayName: 'Build Containers'
      inputs:
        targetType: filePath
        filePath: './src/perfcollect/tests/build-containers.sh'
        workingDirectory: src/perfcollect/tests

    - task: Bash@3
      displayName: 'Run Tests'
      inputs:
        targetType: filePath
        filePath: './src/perfcollect/tests/run-containers.sh'
        workingDirectory: src/perfcollect/tests

